# Generated by Django 5.1.4 on 2026-07-18 06:57

import django.db.models.deletion
import projects.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servers', '0002_server_last_checked_at_server_last_failure_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('framework', models.CharField(choices=[('django_react', 'Django + React')], default='django_react', max_length=30)),
                ('git_repository_url', models.CharField(max_length=500, validators=[projects.validators.validate_git_repository_url])),
                ('branch', models.CharField(default='main', max_length=255)),
                ('domain', models.CharField(blank=True, max_length=253)),
                ('environment_variables', models.JSONField(blank=True, default=dict, validators=[projects.validators.validate_environment_variables])),
                ('docker_compose_path', models.CharField(default='docker-compose.yml', max_length=500, validators=[projects.validators.validate_docker_compose_path])),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_archived', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='servers.server')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
