# Generated by Django 5.1.4 on 2026-07-18 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_branch',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='current_commit',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='project',
            name='encrypted_git_private_key',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='git_cloned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_git_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GitOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('clone', 'Clone'), ('pull', 'Pull'), ('current_commit', 'Current commit'), ('list_branches', 'List branches'), ('select_branch', 'Select branch')], max_length=30)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], max_length=10)),
                ('output', models.TextField(blank=True)),
                ('error_category', models.CharField(blank=True, max_length=50)),
                ('commit_hash', models.CharField(blank=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField()),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='git_operations', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='git_operations', to='projects.project')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
