# Generated by Django 5.1.4 on 2026-07-18 09:44

import django.db.models.deletion
import projects.validators
from cryptography.fernet import Fernet
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.db import migrations, models


def migrate_environment_variables(apps, schema_editor):
    key = getattr(settings, 'ENVIRONMENT_VARIABLE_ENCRYPTION_KEY', None)
    if not key:
        raise ImproperlyConfigured(
            'ENVIRONMENT_VARIABLE_ENCRYPTION_KEY must be configured before migration.'
        )
    try:
        cipher = Fernet(key.encode() if isinstance(key, str) else key)
    except (TypeError, ValueError) as exc:
        raise ImproperlyConfigured(
            'ENVIRONMENT_VARIABLE_ENCRYPTION_KEY must be a valid Fernet key.'
        ) from exc

    Project = apps.get_model('projects', 'Project')
    EnvironmentVariable = apps.get_model('projects', 'EnvironmentVariable')
    rows = []
    for project in Project.objects.iterator():
        for variable_key, value in (project.environment_variables or {}).items():
            rows.append(EnvironmentVariable(
                project_id=project.pk,
                key=variable_key,
                encrypted_value=cipher.encrypt(value.encode()).decode(),
                is_secret=False,
                created_by_id=project.created_by_id,
                updated_by_id=project.updated_by_id,
            ))
    EnvironmentVariable.objects.bulk_create(rows)


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_current_branch_project_current_commit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('key', models.CharField(max_length=255, validators=[projects.validators.validate_environment_variable_key])),
                ('encrypted_value', models.TextField()),
                ('is_secret', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environment_variable_records', to='projects.project')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['key'],
                'constraints': [models.UniqueConstraint(fields=('project', 'key'), name='unique_project_environment_key')],
            },
        ),
        migrations.RunPython(
            migrate_environment_variables, migrations.RunPython.noop
        ),
        migrations.RemoveField(
            model_name='project',
            name='environment_variables',
        ),
        migrations.AlterField(
            model_name='environmentvariable',
            name='project',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='environment_variables',
                to='projects.project',
            ),
        ),
    ]
