# Generated by Django 5.1.4 on 2026-07-18 10:45

import projects.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_remove_project_environment_variables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='django_service_name',
            field=models.CharField(default='backend', max_length=100, validators=[projects.validators.validate_compose_service_name]),
        ),
    ]
