# Generated by Django 5.1.4 on 2026-07-18 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0004_project_django_service_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('deploy', 'Deploy'), ('redeploy', 'Redeploy')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('cancelling', 'Cancelling'), ('cancelled', 'Cancelled'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('previous_commit', models.CharField(blank=True, max_length=64)),
                ('deployed_commit', models.CharField(blank=True, max_length=64)),
                ('cancel_requested_at', models.DateTimeField(blank=True, null=True)),
                ('rollback_status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='not_required', max_length=15)),
                ('rollback_error_category', models.CharField(blank=True, max_length=50)),
                ('error_category', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='projects.project')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments_triggered', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeploymentStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('skipped', 'Skipped')], default='pending', max_length=10)),
                ('error_category', models.CharField(blank=True, max_length=50)),
                ('error_message', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveBigIntegerField(default=0)),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='deployments.deployment')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='deployment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'running', 'cancelling'])), fields=('project',), name='unique_active_project_deployment'),
        ),
        migrations.AddConstraint(
            model_name='deploymentstep',
            constraint=models.UniqueConstraint(fields=('deployment', 'order'), name='unique_deployment_step_order'),
        ),
    ]
