# Generated by Django 5.1.4 on 2026-07-20 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deployments', '0001_initial'),
        ('projects', '0004_project_django_service_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='branch_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='deployment',
            name='cancel_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deployments_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='cancel_requested_by_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='deployment',
            name='project_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='deployment',
            name='repository_url_snapshot',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='deployment',
            name='server_ip_snapshot',
            field=models.CharField(blank=True, max_length=45),
        ),
        migrations.AddField(
            model_name='deployment',
            name='server_name_snapshot',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='deployment',
            name='triggered_by_email_snapshot',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['project', '-created_at'], name='deploy_proj_created_idx'),
        ),
        migrations.AddIndex(
            model_name='deployment',
            index=models.Index(fields=['status', '-created_at'], name='deploy_status_created_idx'),
        ),
    ]
