# Generated by Django 5.1.4 on 2026-07-18 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='last_failure_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='server',
            name='last_latency_ms',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Online', 'Online'), ('Offline', 'Offline')], default='Unknown', max_length=10),
        ),
    ]
