import { useState } from 'react'
import { FileText, Play, RefreshCw, Square } from 'lucide-react'
import { Button, ConfirmModal, DataTable, Modal, SelectField, type TableColumn } from '../components'
import { api } from '../lib/api'
import { formatDate } from '../lib/format'
import { useResource } from '../hooks/useResource'
import type { ContainerStatus, Project } from '../types'
import { ProjectFrame } from './ProjectFrame'
import { Notice, RequestState, StatusBadge } from './shared'

function ContainersContent({ project }: { project: Project }) {
  const resource = useResource<ContainerStatus[]>((signal) => api.get(`/projects/${project.id}/containers/`, signal), [project.id], 10000); const [busy, setBusy] = useState(''); const [removing, setRemoving] = useState<ContainerStatus | null>(null); const [logs, setLogs] = useState<{ service: string; lines: string[] } | null>(null); const [tail, setTail] = useState('200'); const [notice, setNotice] = useState<{ tone: 'success' | 'danger' | 'info'; message: string } | null>(null)
  const action = async (container: ContainerStatus, name: 'start' | 'stop' | 'restart' | 'remove') => { setBusy(`${container.service}-${name}`); try { if (name === 'remove') await api.delete(`/projects/${project.id}/containers/${encodeURIComponent(container.service)}/`); else await api.post(`/projects/${project.id}/containers/${encodeURIComponent(container.service)}/${name}/`); setRemoving(null); setNotice({ tone: 'success', message: `${container.service} ${name} completed.` }); await resource.refetch() } catch (reason) { setNotice({ tone: 'danger', message: (reason as Error).message }) } finally { setBusy('') } }
  const openLogs = async (container: ContainerStatus) => { setBusy(`${container.service}-logs`); try { const result = await api.get<{ service: string; lines: string[] }>(`/projects/${project.id}/containers/${encodeURIComponent(container.service)}/logs/?tail=${tail}`); setLogs(result) } catch (reason) { setNotice({ tone: 'danger', message: (reason as Error).message }) } finally { setBusy('') } }
  const columns: TableColumn<ContainerStatus>[] = [{ key: 'service', heading: 'Service', render: (row) => <><strong>{row.service}</strong><small className="app-block">{row.container_name || 'Not created'}</small></> }, { key: 'state', heading: 'State', render: (row) => <StatusBadge status={row.state} /> }, { key: 'health', heading: 'Health', render: (row) => <StatusBadge status={row.health || 'unknown'} /> }, { key: 'image', heading: 'Image', render: (row) => row.image || '—' }, { key: 'created', heading: 'Created', render: (row) => formatDate(row.created_at) }, { key: 'actions', heading: 'Actions', render: (row) => <div className="app-row-actions"><Button size="small" variant="secondary" icon={<Play size={13} />} disabled={project.is_archived || row.state === 'not_created'} loading={busy === `${row.service}-start`} onClick={() => void action(row, 'start')}>Start</Button><Button size="small" variant="secondary" icon={<Square size={13} />} disabled={project.is_archived || row.state === 'not_created'} onClick={() => void action(row, 'stop')}>Stop</Button><Button size="small" variant="secondary" icon={<RefreshCw size={13} />} disabled={project.is_archived || row.state === 'not_created'} onClick={() => void action(row, 'restart')}>Restart</Button><Button size="small" variant="secondary" icon={<FileText size={13} />} disabled={row.state === 'not_created'} onClick={() => void openLogs(row)}>Logs</Button><Button size="small" variant="danger" disabled={project.is_archived || row.state === 'not_created'} onClick={() => setRemoving(row)}>Remove</Button></div> }]
  return <><Notice value={notice} /><div className="app-toolbar"><p>Live Compose status refreshes every ten seconds while this page is visible.</p><SelectField id="log-tail" label="Log lines" value={tail} onChange={(event) => setTail(event.target.value)}><option value="100">100</option><option value="200">200</option><option value="500">500</option><option value="1000">1000</option></SelectField></div><RequestState loading={resource.loading} error={resource.error} empty={!resource.data?.length}><DataTable caption="Compose services" columns={columns} rows={resource.data || []} rowKey={(row) => row.service} /></RequestState><Modal open={Boolean(logs)} title={`${logs?.service || ''} logs`} description={`Most recent ${tail} timestamped lines. Logs are not stored by LaunchPlatz.`} onClose={() => setLogs(null)} footer={<Button variant="secondary" onClick={() => setLogs(null)}>Close</Button>}><pre className="app-logs">{logs?.lines.join('\n') || 'No log output.'}</pre></Modal><ConfirmModal open={Boolean(removing)} title="Remove container?" description={`Force-stop and remove only ${removing?.service || 'this service'} while preserving images and volumes.`} confirmLabel="Remove container" danger loading={busy.endsWith('-remove')} onClose={() => setRemoving(null)} onConfirm={() => removing && void action(removing, 'remove')} /></>
}
export function ContainersPage() { return <ProjectFrame active="containers">{(project) => <ContainersContent project={project} />}</ProjectFrame> }
