import { useState } from 'react'
import { DataTable, PageHeading, Pagination, SelectField } from '../components'
import { api, type Paginated } from '../lib/api'
import { useResource } from '../hooks/useResource'
import type { Deployment, Project } from '../types'
import { deploymentColumns } from './DeploymentComponents'
import { RequestState } from './shared'

export function DeploymentHistoryPage() { const [project, setProject] = useState(''); const [status, setStatus] = useState(''); const [ordering, setOrdering] = useState('newest'); const [offset, setOffset] = useState(0); const limit = 30; const projects = useResource<Paginated<Project>>((signal) => api.get('/projects/?archived=all&limit=100', signal), []); const query = new URLSearchParams({ limit: String(limit), offset: String(offset), ordering }); if (project) query.set('project', project); if (status) query.set('status', status); const resource = useResource<Paginated<Deployment>>((signal) => api.get(`/deployments/?${query}`, signal), [project, status, ordering, offset]); return <><PageHeading title="Deployment history" description="Immutable audit records and trigger snapshots." /><div className="app-filter-grid"><SelectField id="history-project" label="Project" value={project} onChange={(event) => { setProject(event.target.value); setOffset(0) }}><option value="">All projects</option>{projects.data?.results.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</SelectField><SelectField id="history-status" label="Status" value={status} onChange={(event) => { setStatus(event.target.value); setOffset(0) }}><option value="">All statuses</option>{['pending', 'running', 'cancelling', 'cancelled', 'success', 'failed'].map((item) => <option key={item}>{item}</option>)}</SelectField><SelectField id="history-order" label="Order" value={ordering} onChange={(event) => { setOrdering(event.target.value); setOffset(0) }}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></SelectField></div><RequestState loading={resource.loading} error={resource.error} empty={!resource.data?.results.length}><DataTable caption="Deployment history" columns={deploymentColumns} rows={resource.data?.results || []} rowKey={(row) => String(row.id)} />{resource.data && <Pagination count={resource.data.count} limit={limit} offset={offset} onChange={setOffset} />}</RequestState></> }
