import { useState } from 'react'
import { Eye, EyeOff, Plus, Upload } from 'lucide-react'
import { Button, ConfirmModal, DataTable, Modal, TextArea, TextField, type TableColumn } from '../components'
import { api, ApiError } from '../lib/api'
import { fieldErrors, formatDate } from '../lib/format'
import { useResource } from '../hooks/useResource'
import type { EnvironmentVariable, Project } from '../types'
import { ProjectFrame } from './ProjectFrame'
import { Notice, RequestState } from './shared'

function EnvironmentContent({ project }: { project: Project }) {
  const resource = useResource<EnvironmentVariable[]>((signal) => api.get(`/projects/${project.id}/environment-variables/`, signal), [project.id]); const [revealed, setRevealed] = useState<Set<number>>(new Set()); const [editing, setEditing] = useState<EnvironmentVariable | null>(null); const [formOpen, setFormOpen] = useState(false); const [form, setForm] = useState({ key: '', value: '', is_secret: false }); const [errors, setErrors] = useState<Record<string, string>>({}); const [deleting, setDeleting] = useState<EnvironmentVariable | null>(null); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState<{ tone: 'success' | 'danger' | 'info'; message: string } | null>(null)
  const open = (variable?: EnvironmentVariable) => { setEditing(variable || null); setErrors({}); setForm(variable ? { key: variable.key, value: variable.value, is_secret: variable.is_secret } : { key: '', value: '', is_secret: false }); setFormOpen(true) }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setErrors({}); try { if (editing) await api.patch(`/projects/${project.id}/environment-variables/${editing.id}/`, form); else await api.post(`/projects/${project.id}/environment-variables/`, form); setFormOpen(false); setNotice({ tone: 'success', message: `Variable ${editing ? 'updated' : 'created'}.` }); await resource.refetch() } catch (reason) { setErrors(fieldErrors((reason as ApiError).errors)); setNotice({ tone: 'danger', message: (reason as Error).message }) } finally { setBusy(false) } }
  const remove = async () => { if (!deleting) return; setBusy(true); try { await api.delete(`/projects/${project.id}/environment-variables/${deleting.id}/`); setDeleting(null); setNotice({ tone: 'success', message: 'Variable deleted.' }); await resource.refetch() } catch (reason) { setNotice({ tone: 'danger', message: (reason as Error).message }) } finally { setBusy(false) } }
  const generate = async () => { setBusy(true); try { const result = await api.post<{ variable_count: number; generated_at: string }>(`/projects/${project.id}/environment-variables/generate-env/`); setNotice({ tone: 'success', message: `Generated .env with ${result.variable_count} variables.` }) } catch (reason) { setNotice({ tone: 'danger', message: (reason as Error).message }) } finally { setBusy(false) } }
  const columns: TableColumn<EnvironmentVariable>[] = [{ key: 'key', heading: 'Key', render: (row) => <strong className="app-mono">{row.key}</strong> }, { key: 'value', heading: 'Value', render: (row) => <div className="app-secret"><code>{row.is_secret && !revealed.has(row.id) ? '••••••••••••' : row.value || '(empty)'}</code>{row.is_secret && <button type="button" className="ds-icon-button" aria-label={revealed.has(row.id) ? 'Hide secret' : 'Reveal secret'} onClick={() => setRevealed((current) => { const next = new Set(current); if (next.has(row.id)) next.delete(row.id); else next.add(row.id); return next })}>{revealed.has(row.id) ? <EyeOff size={16} /> : <Eye size={16} />}</button>}</div> }, { key: 'updated', heading: 'Updated', render: (row) => formatDate(row.updated_at) }, { key: 'actions', heading: 'Actions', render: (row) => <div className="app-row-actions"><Button size="small" variant="secondary" disabled={project.is_archived} onClick={() => open(row)}>Edit</Button><Button size="small" variant="danger" disabled={project.is_archived} onClick={() => setDeleting(row)}>Delete</Button></div> }]
  return <><Notice value={notice} /><div className="app-toolbar"><p>Values are decrypted only for this Admin view and are not cached.</p><div className="app-row-actions"><Button variant="secondary" icon={<Upload size={16} />} loading={busy} disabled={project.is_archived || !project.git_cloned_at} onClick={() => void generate()}>Generate .env</Button><Button icon={<Plus size={16} />} disabled={project.is_archived} onClick={() => open()}>Add variable</Button></div></div><RequestState loading={resource.loading} error={resource.error} empty={!resource.data?.length}><DataTable caption="Environment variables" columns={columns} rows={resource.data || []} rowKey={(row) => String(row.id)} /></RequestState><Modal open={formOpen} title={editing ? 'Edit variable' : 'Add variable'} description="All values are encrypted at rest." onClose={() => setFormOpen(false)} footer={<><Button variant="secondary" onClick={() => setFormOpen(false)}>Cancel</Button><Button loading={busy} onClick={() => document.getElementById('env-submit')?.click()}>Save variable</Button></>}><form className="gallery-form" onSubmit={submit}><TextField id="env-key" label="Key" hint="Uppercase letters, digits, and underscores." value={form.key} error={errors.key} onChange={(event) => setForm({ ...form, key: event.target.value.toUpperCase() })} required /><TextArea id="env-value" label="Value" value={form.value} error={errors.value} onChange={(event) => setForm({ ...form, value: event.target.value })} /><label className="app-checkbox"><input type="checkbox" checked={form.is_secret} onChange={(event) => setForm({ ...form, is_secret: event.target.checked })} /> Treat as a secret in the UI</label><button id="env-submit" hidden type="submit" /></form></Modal><ConfirmModal open={Boolean(deleting)} title="Delete environment variable?" description={`${deleting?.key || 'This variable'} will be permanently removed from LaunchPlatz.`} confirmLabel="Delete variable" danger loading={busy} onClose={() => setDeleting(null)} onConfirm={() => void remove()} /></>
}
export function EnvironmentPage() { return <ProjectFrame active="environment">{(project) => <EnvironmentContent project={project} />}</ProjectFrame> }
