import { useState } from 'react'
import { Button, Card, DataTable, SelectField, type TableColumn } from '../components'
import { api, type Paginated } from '../lib/api'
import { formatDate, formatDuration } from '../lib/format'
import { useResource } from '../hooks/useResource'
import type { GitOperation, Project } from '../types'
import { ProjectFrame } from './ProjectFrame'
import { Notice, RequestState, StatusBadge } from './shared'

function GitContent({ project, refreshProject }: { project: Project; refreshProject: () => Promise<unknown> }) {
  const [branches, setBranches] = useState<string[]>([]); const [branch, setBranch] = useState(project.branch); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState<{ tone: 'success' | 'danger' | 'info'; message: string } | null>(null)
  const operations = useResource<Paginated<GitOperation>>((signal) => api.get(`/projects/${project.id}/git/operations/?limit=30`, signal), [project.id])
  const action = async (name: string, path: string, body?: unknown) => { setBusy(name); try { const result = await api.post<{ branches?: string[]; commit?: string }>(`/projects/${project.id}/${path}`, body); if (result.branches) { setBranches(result.branches); if (!result.branches.includes(branch)) setBranch(result.branches[0] || '') } setNotice({ tone: 'success', message: `${name} completed successfully.` }); await Promise.all([refreshProject(), operations.refetch()]) } catch (reason) { setNotice({ tone: 'danger', message: (reason as Error).message }) } finally { setBusy('') } }
  const columns: TableColumn<GitOperation>[] = [{ key: 'action', heading: 'Action', render: (row) => row.action.replaceAll('_', ' ') }, { key: 'status', heading: 'Status', render: (row) => <StatusBadge status={row.status} /> }, { key: 'commit', heading: 'Commit', render: (row) => <span className="app-mono">{row.commit_hash || '—'}</span> }, { key: 'duration', heading: 'Duration', render: (row) => formatDuration(row.duration_ms) }, { key: 'time', heading: 'Started', render: (row) => formatDate(row.started_at) }]
  return <><Notice value={notice} /><Card className="app-action-card"><h2>Repository actions</h2><p>Workspace: ~/launchplatz/projects/{project.id}</p><div className="app-row-actions"><Button loading={busy === 'Clone'} disabled={project.is_archived || Boolean(project.git_cloned_at)} onClick={() => void action('Clone', 'git/clone/')}>Clone</Button><Button variant="secondary" loading={busy === 'Pull'} disabled={project.is_archived || !project.git_cloned_at} onClick={() => void action('Pull', 'git/pull/')}>Pull</Button><Button variant="secondary" loading={busy === 'Inspect commit'} disabled={!project.git_cloned_at} onClick={() => void action('Inspect commit', 'git/current-commit/')}>Inspect commit</Button><Button variant="secondary" loading={busy === 'List branches'} disabled={!project.git_cloned_at} onClick={() => void action('List branches', 'git/branches/')}>Load branches</Button></div>{branches.length > 0 && <div className="app-inline-form"><SelectField id="git-branch" label="Remote branch" value={branch} onChange={(event) => setBranch(event.target.value)}>{branches.map((item) => <option key={item}>{item}</option>)}</SelectField><Button disabled={project.is_archived || !branch} loading={busy === 'Select branch'} onClick={() => void action('Select branch', 'git/select-branch/', { branch })}>Select branch</Button></div>}</Card><section className="app-section"><h2>Git operation history</h2><RequestState loading={operations.loading} error={operations.error} empty={!operations.data?.results.length}><DataTable caption="Git operations" columns={columns} rows={operations.data?.results || []} rowKey={(row) => String(row.id)} /></RequestState></section></>
}
export function GitPage() { return <ProjectFrame active="git">{(project, refetch) => <GitContent project={project} refreshProject={refetch} />}</ProjectFrame> }
