export type ApiEnvelope<T> = { success: true; message: string; data: T; status_code: number }
export type ApiFailure = { success: false; message: string; errors: unknown; status_code: number }
export type Paginated<T> = { count: number; next: string | null; previous: string | null; results: T[] }

export type UserProfile = { id: number; first_name: string; last_name: string; email: string; phone: string; role: number; is_verified: boolean; is_approved: boolean; is_active: boolean }
export type ServerRecord = { id: number; name: string; ip_address: string; ssh_port: number; username: string; status: 'Online' | 'Offline' | 'Unknown'; last_checked_at: string | null; last_latency_ms: number | null; last_failure_reason: string; created_at: string; updated_at: string }
export type Project = { id: number; server: number; name: string; framework: string; framework_display: string; git_repository_url: string; branch: string; domain: string; docker_compose_path: string; django_service_name: string; is_archived: boolean; archived_at: string | null; git_cloned_at: string | null; current_branch: string; current_commit: string; last_git_synced_at: string | null; created_at: string; updated_at: string }
export type RoutingRoute = { id: number; project_id: number; hostname: string; normalized_hostname: string; service_name: string; internal_port: number; desired_enabled: boolean; tls_enabled: boolean; dns_status: string; dns_last_checked_at: string | null; resolved_addresses: string[]; dns_error: string; expected_address: string; observed_status: string; configuration_revision: string; last_reconciled_at: string | null; last_error: string; created_at: string; updated_at: string }
export type DeploymentStatus = 'pending' | 'running' | 'cancelling' | 'cancelled' | 'success' | 'failed'
export type DeploymentStep = { id: number; order: number; name: string; status: string; error_category: string; error_message: string; started_at: string | null; completed_at: string | null; duration_ms: number }
export type Deployment = { id: number; project: number; trigger: 'deploy' | 'redeploy'; status: DeploymentStatus; previous_commit: string; deployed_commit: string; rollback_status: string; rollback_error_category: string; error_category: string; error_message?: string; started_at: string | null; completed_at: string | null; duration_ms: number; created_at: string; project_name_snapshot: string; server_name_snapshot: string; server_ip_snapshot: string; branch_snapshot: string; repository_url_snapshot: string; triggered_by_email_snapshot: string; cancel_requested_at?: string | null; steps?: DeploymentStep[] }
export type GitOperation = { id: number; action: string; status: string; output: string; error_category: string; commit_hash: string; duration_ms: number; started_at: string; completed_at: string; initiated_by: number }
export type EnvironmentVariable = { id: number; key: string; value: string; is_secret: boolean; created_at: string; updated_at: string }
export type ContainerStatus = { service: string; container_id: string; container_name: string; image: string; state: string; health: string; exit_code: number | null; created_at: string; ports: Array<Record<string, unknown>> }
export type DashboardData = { servers: { total: number; online: number; offline: number; unknown: number }; projects: { total: number; active: number; archived: number }; deployments: Record<DeploymentStatus | 'total', number>; recent_deployments: Deployment[] }
