from .base import *


DEBUG = True
SECRET_KEY = 'django-test-secret-key'
ALLOWED_HOSTS = ['testserver']
SERVER_CREDENTIAL_ENCRYPTION_KEY = (
    'MDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDA='
)
SSH_CONNECTION_TIMEOUT = 30
GIT_CREDENTIAL_ENCRYPTION_KEY = (
    'MTExMTExMTExMTExMTExMTExMTExMTExMTExMTExMTE='
)
GIT_OPERATION_TIMEOUT = 120
ENVIRONMENT_VARIABLE_ENCRYPTION_KEY = (
    'MjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjI='
)
CELERY_BROKER_URL = 'memory://'
CELERY_RESULT_BACKEND = 'cache+memory://'
CELERY_TASK_ALWAYS_EAGER = True
CELERY_TASK_EAGER_PROPAGATES = True
DEPLOYMENT_COMMAND_TIMEOUT = 10
DEPLOYMENT_HEALTH_TIMEOUT = 1
DOCKER_ACTION_TIMEOUT = 10
DOCKER_STOP_TIMEOUT = 1
DOCKER_LOG_MAX_LINES = 1000
DOCKER_LOG_MAX_CHARACTERS = 200000

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'test.sqlite3',
    }
}

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.MD5PasswordHasher',
]
